name: Build and Deploy Docker Image

on:
  push:
    branches: [ main ]

jobs:

  Deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Code Checkout
      uses: actions/checkout@v2
    - name: GHCR Login
      uses: docker/login-action@v1
      with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PACKAGE_ACCESS_TOKEN }}
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
          context: .
          push: true
          tags: |
            ghcr.io/mP3nn/p10i_frontend:latest
